// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace icbincvdt.Migrations
{
    [DbContext(typeof(RazorPagesCVContext))]
    partial class RazorPagesCVContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("icbincvdt.Models.CV", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("CV");
                });

            modelBuilder.Entity("icbincvdt.Models.Education", b =>
                {
                    b.Property<int>("EducationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CVID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EducationText")
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationYearRange")
                        .HasColumnType("TEXT");

                    b.HasKey("EducationID");

                    b.HasIndex("CVID");

                    b.ToTable("Education");
                });

            modelBuilder.Entity("icbincvdt.Models.Experience", b =>
                {
                    b.Property<int>("ExperienceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CVID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExperienceText")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExperienceTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExperienceYearRange")
                        .HasColumnType("TEXT");

                    b.HasKey("ExperienceID");

                    b.HasIndex("CVID");

                    b.ToTable("Experience");
                });

            modelBuilder.Entity("icbincvdt.Models.Reference", b =>
                {
                    b.Property<int>("ReferenceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CVID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenceName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReferencePhoneNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReferenceID");

                    b.HasIndex("CVID");

                    b.ToTable("Reference");
                });

            modelBuilder.Entity("icbincvdt.Models.Skill", b =>
                {
                    b.Property<int>("SkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CVID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkillText")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillTitle")
                        .HasColumnType("TEXT");

                    b.HasKey("SkillID");

                    b.HasIndex("CVID");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("icbincvdt.Models.Education", b =>
                {
                    b.HasOne("icbincvdt.Models.CV", null)
                        .WithMany("Education")
                        .HasForeignKey("CVID");
                });

            modelBuilder.Entity("icbincvdt.Models.Experience", b =>
                {
                    b.HasOne("icbincvdt.Models.CV", null)
                        .WithMany("Experience")
                        .HasForeignKey("CVID");
                });

            modelBuilder.Entity("icbincvdt.Models.Reference", b =>
                {
                    b.HasOne("icbincvdt.Models.CV", null)
                        .WithMany("Reference")
                        .HasForeignKey("CVID");
                });

            modelBuilder.Entity("icbincvdt.Models.Skill", b =>
                {
                    b.HasOne("icbincvdt.Models.CV", null)
                        .WithMany("Skill")
                        .HasForeignKey("CVID");
                });
#pragma warning restore 612, 618
        }
    }
}
